include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  rules:
    - prefer_relative_imports
    - sort_pub_dependencies
analyzer:
  plugins:
    - custom_lint
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
formatter:
  page_width: 120
