name: bloc_template_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  drift: ^2.19.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.3
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  sqlite3_flutter_libs: ^0.5.24
  supabase_flutter: ^2.5.2
  uuid: ^4.4.2
  vector_graphics: ^1.1.11+1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  drift_dev: ^2.19.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  mocktail: ^1.0.4
  slang_build_runner: ^3.29.0
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler
